spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server  # Eureka’daki adı
      profile: dev
  application:
    name: address-service
  datasource:
    url: jdbc:postgresql://postgres:5432/addressdb
    username: postgres
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
server:
  port: 1410
