spring:
  application:
    name: address-service
  datasource:
    url: jdbc:postgresql://postgres:5432/addressdb
    username: postgres
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 1410
