server:
  port: 8890

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tolgamercan/yasamevimgatewayconfigrepo.git
          default-label: master
          clone-on-start: true
    profiles:
      active: dev
