spring:
  main:
    allow-bean-definition-overriding: true # Önemli!
  application:
    name: gateway
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  cloud:
    gateway:
      routes: [] # Mongo'dan okunacak

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/myrealm

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8888
