spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes: [] # Mongo'dan okunacak

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/myrealm

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8888
