server:
  port: 1400

spring:
  application:
    name: route-management-service
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: gatewaydb
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
