server:
  port: 1400

spring:
  application:
    name: route-management-service
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: gatewaydb
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
